# Generated by Django 2.1.5 on 2019-02-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='third_name',
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
    ]
